"""updated transaction

Revision ID: 08cb43104480
Revises: 203b8e7911d1
Create Date: 2024-10-05 13:22:49.932250

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08cb43104480"
down_revision: Union[str, None] = "203b8e7911d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("exttrid", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "exttrid")
    # ### end Alembic commands ###
