"""updated users

Revision ID: 203b8e7911d1
Revises: fff12564cbea
Create Date: 2024-10-04 22:08:35.377917

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "203b8e7911d1"
down_revision: Union[str, None] = "fff12564cbea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("active_status", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("del_status", sa.Boolean(), nullable=True))
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_column("users", "del_status")
    op.drop_column("users", "active_status")
    # ### end Alembic commands ###
